version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./configs:/app/configs
      - ./TICKERS.csv:/app/TICKERS.csv
    environment:
      - GOTMPDIR=/app/temp_builds
      - CONFIG_PATH=/app/configs/config.yaml 